# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/federated.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/federated.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/federated.proto\x12\tfederated\"\x07\n\x05\x45mpty\"3\n\x0cRoundRequest\x12\x10\n\x08round_id\x18\x01 \x01(\x05\x12\x11\n\tclient_id\x18\x02 \x01(\t\"?\n\x0cModelWeights\x12\x10\n\x08round_id\x18\x01 \x01(\x05\x12\x1d\n\x15serialized_state_dict\x18\x02 \x01(\x0c\"F\n\nTimingInfo\x12\x13\n\x0b\x64ownload_ms\x18\x01 \x01(\x01\x12\x10\n\x08train_ms\x18\x02 \x01(\x01\x12\x11\n\tupload_ms\x18\x03 \x01(\x01\"\xf3\x01\n\x0c\x43lientUpdate\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x10\n\x08round_id\x18\x02 \x01(\x05\x12\x1d\n\x15serialized_state_dict\x18\x03 \x01(\x0c\x12\x13\n\x0bnum_samples\x18\x04 \x01(\x05\x12\x12\n\ntrain_loss\x18\x05 \x01(\x01\x12%\n\x06timing\x18\x06 \x01(\x0b\x32\x15.federated.TimingInfo\x12\x10\n\x08hostname\x18\x07 \x01(\t\x12\x10\n\x08gpu_name\x18\x08 \x01(\t\x12\x15\n\rtorch_version\x18\t \x01(\t\x12\x14\n\x0c\x63uda_version\x18\n \x01(\t\"F\n\x0b\x41\x63kResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\x0cserver_round\x18\x03 \x01(\x05\"\xc7\x01\n\x0bRoundStatus\x12\x15\n\rcurrent_round\x18\x01 \x01(\x05\x12+\n\x05state\x18\x02 \x01(\x0e\x32\x1c.federated.RoundStatus.State\x12\x18\n\x10num_rounds_total\x18\x03 \x01(\x05\"Z\n\x05State\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07WAITING\x10\x01\x12\x0c\n\x08TRAINING\x10\x02\x12\x0f\n\x0b\x41GGREGATING\x10\x03\x12\x0e\n\nEVALUATING\x10\x04\x12\x08\n\x04\x44ONE\x10\x05\x32\xd4\x01\n\x11\x46\x65\x64\x65ratedLearning\x12\x42\n\x0eGetGlobalModel\x12\x17.federated.RoundRequest\x1a\x17.federated.ModelWeights\x12?\n\x0cSubmitUpdate\x12\x17.federated.ClientUpdate\x1a\x16.federated.AckResponse\x12:\n\x0eGetRoundStatus\x12\x10.federated.Empty\x1a\x16.federated.RoundStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.federated_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=36
  _globals['_EMPTY']._serialized_end=43
  _globals['_ROUNDREQUEST']._serialized_start=45
  _globals['_ROUNDREQUEST']._serialized_end=96
  _globals['_MODELWEIGHTS']._serialized_start=98
  _globals['_MODELWEIGHTS']._serialized_end=161
  _globals['_TIMINGINFO']._serialized_start=163
  _globals['_TIMINGINFO']._serialized_end=233
  _globals['_CLIENTUPDATE']._serialized_start=236
  _globals['_CLIENTUPDATE']._serialized_end=479
  _globals['_ACKRESPONSE']._serialized_start=481
  _globals['_ACKRESPONSE']._serialized_end=551
  _globals['_ROUNDSTATUS']._serialized_start=554
  _globals['_ROUNDSTATUS']._serialized_end=753
  _globals['_ROUNDSTATUS_STATE']._serialized_start=663
  _globals['_ROUNDSTATUS_STATE']._serialized_end=753
  _globals['_FEDERATEDLEARNING']._serialized_start=756
  _globals['_FEDERATEDLEARNING']._serialized_end=968
# @@protoc_insertion_point(module_scope)
